fade_lights:
  name: Fade lights
  description: Fades lights to a desired level over a specified transition period.
  fields:
    entity_id:
      name: Entity ID
      description: Entity ID of a light or light group.
      required: true
      example: "light.bedroom"
      selector:
        entity:
          domain: light
          multiple: true
    brightness_pct:
      name: Brightness percentage
      description: Integer value from 0 to 100 representing the desired final brightness level as a percentage.
      required: false
      default: 40
      example: 75
      selector:
        number:
          min: 0
          max: 100
          mode: slider
          unit_of_measurement: "%"
    transition:
      name: Transition time
      description: Transition time for fading in seconds. Accepts decimal values, e.g., 0.5 for 500ms.
      required: false
      default: 3
      example: "0.5"
      selector:
        number:
          min: 0
          max: 3600
          step: 0.1
          mode: box
          unit_of_measurement: "s"
